server:
  port: 8080

spring:
  application:
    name: aiflow
  datasource:
    url: jdbc:postgresql://localhost:5432/aiflow
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true